// This file was auto-generated by ML.NET Model Builder. 

using System;
using Study_mlML.Model;

namespace Study_mlML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            //Add input data
            var input = new ModelInput();
            input.SentimentText = "That is rude.";

            //Load model and predict output of sample data
            ModelOutput result = ConsumeModel.Predict(input);
            Console.WriteLine($"Text: {input.SentimentText}\nIs Toxic: {result.Prediction}");
        }
    }
}
